#!/usr/bin/env python3
"""
Regenerate the #schedule section of index.html from the workshop-logistics CSV.

Usage:
    python3 scripts/build_schedule.py "Workshop logistics - schedule.csv"

This overwrites the HTML between the
    <!-- SCHEDULE:START ... -->
and
    <!-- SCHEDULE:END -->
markers inside index.html with freshly generated <div class="schedule-day-block">
markup. Nothing outside those markers is touched, so re-run this any time you get
an updated version of the CSV.

--- CSV -> HTML mapping rules (keep this in sync with reality) ---

Expected columns (row[0] is always a leading blank column from the export):
    "", Start, End, Chair, Type, Speaker, Title, Abstract

Any rows before the first day header (e.g. a "Zoom Link for all meetings:" note
row) are ignored. The Chair column is parsed but not currently displayed on the
site.

Day headers: a row whose Start-column cell contains "(Conference)" or
"(Hackathon)" (e.g. "MONDAY (Conference)") starts a new day block. The DAY_LABELS
dict below maps the recognized day name to the full heading text + date shown on
the site -- update it if the workshop dates ever change.

Row handling by Type (case-insensitive):
    - "Conference dinner"          -> dropped entirely, not shown on the site.
    - "" (blank) + Wednesday/Thursday hackathon rows -> the descriptive text
      actually lives in the *Speaker* column for these rows (that's just how the
      hackathon block is laid out in the sheet). Rendered as a single plain-text
      session line, no separate speaker/title.
    - "Coffee break" / "Lunch break" -> rendered as a shaded, spanning break row.
    - "Discussion"                  -> the discussion *topic* (not a person) is
      read from the Title column if present, falling back to the Speaker column
      (an earlier version of the sheet put it there instead). Rendered as the
      session's title line; no speaker shown.
    - "KAAI Contributed talk" / "Contributed talk" -> both normalized to the
      single displayed label "Contributed talk".
    - Everything else (Welcome & introduction, Invited talk, ...) -> shown as-is,
      with Title as a sub-line and Speaker in the right-hand column.

Title / Speaker text:
    - Empty or literal "TBA" (any case) -> displayed as "TBA".

Abstracts:
    - When the Abstract column is non-empty, the title is rendered as a native
      <details><summary> so the abstract is hidden by default and expands on
      click; talks with no abstract just show plain title text. Multi-paragraph
      abstracts (blank line in the cell) become separate <p> tags.
"""

import csv
import html
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
INDEX_HTML = REPO_ROOT / "index.html"

START_MARKER = "<!-- SCHEDULE:START (auto-generated by scripts/build_schedule.py -- do not hand-edit between these markers) -->"
END_MARKER = "<!-- SCHEDULE:END -->"

DAY_LABELS = {
    "monday": "Monday, August 31 &middot; Conference Day 1",
    "tuesday": "Tuesday, September 1 &middot; Conference Day 2",
    "wednesday": "Wednesday, September 2 &middot; Hackathon Day 1",
    "thursday": "Thursday, September 3 &middot; Hackathon Day 2",
}

BREAK_TYPES = {"coffee break", "lunch break"}
SKIPPED_TYPES = {"conference dinner"}
CONTRIBUTED_ALIASES = {"contributed talk", "kaai contributed talk"}

TYPE_CLASS = {
    "welcome & introduction": "opening",
    "invited talk": "invited",
    "contributed talk": "contributed",
    "discussion": "discussion",
}


def clean(s):
    return (s or "").strip()


def esc(s):
    return html.escape(s, quote=False)


def or_tba(s):
    s = clean(s)
    return esc(s) if s and s.lower() != "tba" else "TBA"


def title_html(title, abstract):
    title_text = or_tba(title)
    abstract = clean(abstract)
    if not abstract:
        return f'<span class="session-title">{title_text}</span>'
    paragraphs = "".join(
        f"<p>{esc(p.strip())}</p>" for p in re.split(r"\n\s*\n", abstract) if p.strip()
    )
    return (
        f'<details class="abstract-toggle">'
        f'<summary class="session-title">{title_text}</summary>'
        f'<div class="session-abstract">{paragraphs}</div>'
        f"</details>"
    )


def fmt_time_range(start, end):
    def parts(t):
        t = t.strip()
        m = re.match(r"^(\d{1,2}:\d{2})\s*(AM|PM)$", t, re.I)
        if not m:
            return t, ""
        return m.group(1), m.group(2).lower()

    s_time, s_period = parts(start)
    e_time, e_period = parts(end)
    if s_period and s_period == e_period:
        return f"{s_time} &ndash; {e_time} {e_period}"
    return f"{s_time} {s_period} &ndash; {e_time} {e_period}".strip()


def day_key(start_cell):
    m = re.match(r"^(monday|tuesday|wednesday|thursday)\b", start_cell.strip(), re.I)
    return m.group(1).lower() if m else None


def build_day_block(day, rows):
    lines = []
    lines.append('      <div class="schedule-day-block">')
    lines.append(f"        <h3>{DAY_LABELS[day]}</h3>")
    lines.append('        <div class="schedule-table-wrap">')
    lines.append('          <table class="schedule-table">')
    lines.append("            <tbody>")

    for start, end, chair, rtype, speaker, title, abstract in rows:
        del chair  # parsed but not displayed
        rtype_norm = clean(rtype).lower()
        time_html = fmt_time_range(start, end)

        if rtype_norm in SKIPPED_TYPES:
            continue

        if rtype_norm in BREAK_TYPES:
            lines.append(
                f'              <tr class="break-row"><td class="time">{time_html}</td>'
                f'<td class="session break" colspan="2">{esc(clean(rtype))}</td></tr>'
            )
            continue

        if rtype_norm == "":
            # Hackathon rows: the label lives in the Speaker column.
            label = esc(clean(speaker) or clean(title))
            lines.append(
                f'              <tr><td class="time">{time_html}</td>'
                f'<td class="session hackathon" colspan="2">{label}</td></tr>'
            )
            continue

        if rtype_norm == "discussion":
            css_class = TYPE_CLASS["discussion"]
            topic = or_tba(clean(title) or clean(speaker))
            lines.append(
                f'              <tr><td class="time">{time_html}</td>'
                f'<td class="session {css_class}"><span class="session-type">Discussion</span>'
                f'<span class="session-title">{topic}</span></td>'
                f'<td class="speaker"></td></tr>'
            )
            continue

        display_type = "Contributed talk" if rtype_norm in CONTRIBUTED_ALIASES else esc(clean(rtype))
        css_class = TYPE_CLASS.get(rtype_norm, TYPE_CLASS.get("contributed talk") if rtype_norm in CONTRIBUTED_ALIASES else "contributed")
        speaker_html = or_tba(speaker)
        lines.append(
            f'              <tr><td class="time">{time_html}</td>'
            f'<td class="session {css_class}"><span class="session-type">{display_type}</span>'
            f'{title_html(title, abstract)}</td>'
            f'<td class="speaker known">{speaker_html}</td></tr>'
        )

    lines.append("            </tbody>")
    lines.append("          </table>")
    lines.append("        </div>")
    lines.append("      </div>")
    return "\n".join(lines)


def parse_csv(csv_path):
    with open(csv_path, newline="", encoding="utf-8") as f:
        rows = list(csv.reader(f))

    days = {}
    current_day = None

    for row in rows:
        if not row:
            continue
        row = row[1:] if len(row) > 0 else row  # drop leading blank export column
        row += [""] * (7 - len(row))  # Start, End, Chair, Type, Speaker, Title, Abstract
        start = clean(row[0])

        if "duration (mins)" in ",".join(row).lower():
            break  # reached the trailing legend table

        dk = day_key(start)
        if dk:
            current_day = dk
            days.setdefault(current_day, [])
            continue

        if start.lower() in ("start", ""):
            continue  # header row or blank separator

        if current_day is None:
            continue

        days[current_day].append(tuple(row[:7]))

    return days


def main():
    if len(sys.argv) != 2:
        print(f"usage: {sys.argv[0]} <schedule.csv>", file=sys.stderr)
        sys.exit(1)

    days = parse_csv(sys.argv[1])

    blocks = []
    for day in ("monday", "tuesday", "wednesday", "thursday"):
        if day in days:
            blocks.append(build_day_block(day, days[day]))
    generated = "\n\n".join(blocks)

    html = INDEX_HTML.read_text(encoding="utf-8")
    if START_MARKER not in html or END_MARKER not in html:
        print("Could not find SCHEDULE:START/END markers in index.html", file=sys.stderr)
        sys.exit(1)

    pattern = re.compile(re.escape(START_MARKER) + r".*?" + re.escape(END_MARKER), re.S)
    replacement = f"{START_MARKER}\n{generated}\n      {END_MARKER}"
    new_html = pattern.sub(lambda _: replacement, html, count=1)
    INDEX_HTML.write_text(new_html, encoding="utf-8")
    print(f"Updated {INDEX_HTML} with {sum(len(v) for v in days.values())} CSV rows across {len(blocks)} day(s).")


if __name__ == "__main__":
    main()
